baseURL = "/"
languageCode = "en-us"
title = "It's a Wedding!!!"
theme = "universal"
sectionPagesMenu = "main"

Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/wtatum/hugo-wedding"
  linkedin = ""
  date_format = "January 2, 2006"
